version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "parking-lot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16cxpssmb5ep1"
s3_prefix = "parking-lot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
